import { useState } from "react";
import { ActionItem, api } from "./api";

export function ActionsPage({items,csrf,refresh}:{items:ActionItem[];csrf:string;refresh:()=>Promise<void>}) {
  const [busy,setBusy]=useState(""),[error,setError]=useState("");
  async function build(item:ActionItem){setBusy(item.finding_id);setError("");try{await api.buildRemediationPlan(item.finding_id,csrf);await refresh()}catch(reason){setError(reason instanceof Error?reason.message:"Unable to build plan")}finally{setBusy("")}}
  async function approve(item:ActionItem){if(!item.plan||!window.confirm(`Approve upgrading ${item.plan.package_name} from ${item.plan.installed_version} to ${item.plan.target_version} on ${item.device_name||item.address}? This records approval but does not execute yet.`))return;setBusy(item.plan.id);setError("");try{await api.approveRemediationPlan(item.plan.id,csrf);await refresh()}catch(reason){setError(reason instanceof Error?reason.message:"Unable to approve plan")}finally{setBusy("")}}
  return <><header><div><p className="eyebrow">IDENTIFY · APPROVE · VERIFY</p><h1>Action Center</h1><p>Prioritized Linux remediation with exact package evidence and an auditable approval gate.</p></div></header><div className="notice panel"><b>Execution safety:</b> Approved plans are persisted and audited, but remain non-executing until the restricted root helper and signed agent delivery protocol are installed.</div>{error&&<div className="error storage-error">{error}</div>}{items.length===0?<div className="empty-state panel"><h2>No active remediation work</h2><p>Open or investigating vulnerability findings will appear here.</p></div>:<div className="action-list">{items.map(item=><article className={`panel action-item ${item.known_exploited?"urgent":""}`} key={item.finding_id}><div className="action-priority"><strong>{item.priority}</strong><small>PRIORITY</small></div><div><div className="action-title"><span className={`severity ${item.severity}`}>{item.severity}</span><h2>{item.cve_id}</h2>{item.known_exploited&&<span className="kev-badge">CISA KEV</span>}</div><p><b>{item.device_name||item.address}</b> · {item.address} · Device criticality: {item.device_criticality||"unassigned"}</p>{item.affected_package&&<p className="package-evidence"><b>{item.affected_package}</b> {item.installed_version||"unknown"} → {item.fixed_version||"fix not published"}</p>}<p>{item.required_action||"Review the vendor advisory and package evidence."}{item.action_due&&` Due ${item.action_due}.`}</p>{item.plan?<div className="automation-locked"><b>Plan {item.plan.status}</b><span>{item.plan.operation}: {item.plan.package_name} {item.plan.installed_version} → {item.plan.target_version}</span></div>:<div className="automation-locked"><b>{item.automation_ready?"Plan available":"Automation locked"}</b><span>{item.automation_blocker}</span></div>}</div><div className="action-state"><span>{item.finding_status.replace("_"," ")}</span>{!item.plan?<button onClick={()=>void build(item)} disabled={!item.automation_ready||busy===item.finding_id}>{busy===item.finding_id?"Building…":"Build playbook"}</button>:item.plan.status==="draft"?<button className="primary compact" onClick={()=>void approve(item)} disabled={busy===item.plan.id}>{busy===item.plan.id?"Approving…":"Review & approve"}</button>:<button disabled>{item.plan.status==="approved"?"Awaiting executor":item.plan.status}</button>}</div></article>)}</div>}</>;
}
