import { useEffect, useState } from "react";
import { Agent, api, Device } from "./api";

const age=(seconds:number|null)=>seconds===null?"—":seconds>=86400?`${Math.floor(seconds/86400)}d`:seconds>=3600?`${Math.floor(seconds/3600)}h`:`${Math.floor(seconds/60)}m`;
const bytes=(value:number|null)=>value===null?"—":`${(value/1_073_741_824).toFixed(1)} GB`;

export function AgentsPage({agents,devices,csrf,refresh}:{agents:Agent[];devices:Device[];csrf:string;refresh:()=>Promise<void>}) {
  const [deviceId,setDeviceId]=useState(devices[0]?.id||""),[command,setCommand]=useState(""),[error,setError]=useState("");
  const available=devices.filter(device=>!agents.some(agent=>agent.device_id===device.id));
  useEffect(()=>{if(!available.some(device=>device.id===deviceId))setDeviceId(available[0]?.id||"")},[agents,devices,deviceId,available]);
  useEffect(()=>{const timer=window.setInterval(()=>void refresh(),10000);return()=>window.clearInterval(timer)},[refresh]);
  async function enroll(){setError("");try{const result=await api.createAgentEnrollment(deviceId,csrf),url=window.location.origin,http=url.startsWith("http://");setCommand(`mkdir -p /tmp/sentinel-agent-install && cd /tmp/sentinel-agent-install\ncurl -fsSLO https://raw.githubusercontent.com/xyciasav/sentinel-home/main/agents/linux/sentinel_agent.py\ncurl -fsSLO https://raw.githubusercontent.com/xyciasav/sentinel-home/main/agents/linux/install.sh\nsudo env SENTINEL_URL='${url}' SENTINEL_ENROLLMENT_TOKEN='${result.enrollment_token}' SENTINEL_ALLOW_HTTP='${http}' sh ./install.sh`)}catch(reason){setError(reason instanceof Error?reason.message:"Unable to create enrollment")}}
  async function remove(agent:Agent){if(!window.confirm(`Remove the agent for ${agent.device_name}? Its credential, metrics, and package inventory will be deleted. The Linux service must be uninstalled separately.`))return;setError("");try{await api.deleteAgent(agent.id,csrf);await refresh()}catch(reason){setError(reason instanceof Error?reason.message:"Unable to remove agent")}}
  return <><header><div><p className="eyebrow">ENDPOINT TELEMETRY</p><h1>Agents</h1><p>Authenticated Linux agents report system health and installed packages every 15 seconds.</p></div></header><section className="panel agent-enroll"><div><h2>Connect a Linux system</h2><p>Select an existing device. Enrollment tokens are single-use and expire after 30 minutes.</p></div><select value={deviceId} onChange={event=>setDeviceId(event.target.value)}>{available.length===0?<option value="">No unenrolled devices</option>:available.map(device=><option key={device.id} value={device.id}>{device.display_name} · {device.address}</option>)}</select><button className="primary compact" onClick={()=>void enroll()} disabled={!deviceId}>Generate install command</button></section>{error&&<div className="error storage-error">{error}</div>}{agents.length===0?<div className="empty-state panel"><h2>No agents connected</h2><p>Add Linux servers to Devices first, then generate an enrollment command above.</p></div>:<div className="agent-grid">{agents.map(agent=><article className="panel agent-card" key={agent.id}><div className="panel-title"><div><p className="eyebrow">{agent.platform} · AGENT {agent.version}</p><h2><i className={`status-dot ${agent.connected?"online":"offline"}`}/>{agent.device_name}</h2></div><div className="agent-card-actions"><span>{agent.connected?"Connected":"Disconnected"}</span><button className="danger" onClick={()=>void remove(agent)}>Remove</button></div></div><div className="agent-metrics"><div><small>CPU</small><b>{agent.cpu_percent??"—"}%</b></div><div><small>Memory</small><b>{agent.memory_percent??"—"}%</b></div><div><small>Disk</small><b>{agent.disk_percent??"—"}%</b></div><div><small>Disk free</small><b>{bytes(agent.disk_free_bytes)}</b></div><div><small>Uptime</small><b>{age(agent.uptime_seconds)}</b></div><div><small>Packages</small><b>{agent.package_count.toLocaleString()}</b></div></div><small>Last heartbeat: {agent.last_heartbeat_at?new Date(agent.last_heartbeat_at).toLocaleString():"never"}</small></article>)}</div>}{command&&<div className="modal-backdrop"><div className="panel install-command"><div className="panel-title"><div><p className="eyebrow">ONE-TIME ENROLLMENT</p><h2>Run on the selected Linux system</h2></div><button className="close" onClick={()=>{setCommand("");void refresh()}}>×</button></div><p>Review the downloaded scripts, then run these commands. The token expires in 30 minutes and cannot be shown again.</p><pre>{command}</pre><button className="primary compact" onClick={()=>void navigator.clipboard.writeText(command)}>Copy command</button></div></div>}</>;
}
