import { useEffect, useState } from "react";
import { Agent, AgentMetric, api, Device, InstalledPackage } from "./api";

const age = (seconds:number|null) => seconds===null ? "—" : seconds>=86400 ? `${Math.floor(seconds/86400)}d` : seconds>=3600 ? `${Math.floor(seconds/3600)}h` : `${Math.floor(seconds/60)}m`;
const bytes = (value:number|null) => value===null ? "—" : `${(value/1_073_741_824).toFixed(1)} GB`;

export function AgentsPage({agents,devices,csrf,refresh}:{agents:Agent[];devices:Device[];csrf:string;refresh:()=>Promise<void>}) {
  const available=devices.filter(device=>!agents.some(agent=>agent.device_id===device.id));
  const [deviceId,setDeviceId]=useState(available[0]?.id||"");
  const [command,setCommand]=useState(""),[commandMode,setCommandMode]=useState<"enroll"|"update">("enroll");
  const [error,setError]=useState(""),[message,setMessage]=useState(""),[scanning,setScanning]=useState("");
  const [selected,setSelected]=useState<Agent|null>(null),[metrics,setMetrics]=useState<AgentMetric[]>([]),[packages,setPackages]=useState<InstalledPackage[]>([]),[packageSearch,setPackageSearch]=useState("");

  useEffect(()=>{if(!available.some(device=>device.id===deviceId))setDeviceId(available[0]?.id||"")},[agents,devices,deviceId,available]);

  async function enroll(){setError("");try{const result=await api.createAgentEnrollment(deviceId,csrf),url=window.location.origin,http=url.startsWith("http://");setCommandMode("enroll");setCommand(`install_dir=$(mktemp -d /tmp/sentinel-agent-install.XXXXXX) && cd "$install_dir"\ncurl -fsSL 'https://raw.githubusercontent.com/xyciasav/sentinel-home/main/agents/linux/sentinel_agent.py?v=0.6.0' -o sentinel_agent.py\ncurl -fsSL 'https://raw.githubusercontent.com/xyciasav/sentinel-home/main/agents/linux/sentinel_remediate.py?v=0.3.1' -o sentinel_remediate.py\ncurl -fsSL 'https://raw.githubusercontent.com/xyciasav/sentinel-home/main/agents/linux/sentinel_containers.py?v=0.6.0' -o sentinel_containers.py\ncurl -fsSL 'https://raw.githubusercontent.com/xyciasav/sentinel-home/main/agents/linux/install.sh?v=0.6.0' -o install.sh\nsudo env SENTINEL_URL='${url}' SENTINEL_ENROLLMENT_TOKEN='${result.enrollment_token}' SENTINEL_ALLOW_HTTP='${http}' sh ./install.sh`)}catch(reason){setError(reason instanceof Error?reason.message:"Unable to create enrollment")}}
  function updateCommand(){setCommandMode("update");setCommand("update_dir=$(mktemp -d /tmp/sentinel-agent-update.XXXXXX) && cd \"$update_dir\"\ncurl -fsSL 'https://raw.githubusercontent.com/xyciasav/sentinel-home/main/agents/linux/sentinel_agent.py?v=0.6.0' -o sentinel_agent.py\ncurl -fsSL 'https://raw.githubusercontent.com/xyciasav/sentinel-home/main/agents/linux/sentinel_remediate.py?v=0.3.1' -o sentinel_remediate.py\ncurl -fsSL 'https://raw.githubusercontent.com/xyciasav/sentinel-home/main/agents/linux/sentinel_containers.py?v=0.6.0' -o sentinel_containers.py\ncurl -fsSL 'https://raw.githubusercontent.com/xyciasav/sentinel-home/main/agents/linux/update.sh?v=0.6.0' -o update.sh\nsudo sh ./update.sh")}
  async function remove(agent:Agent){if(!window.confirm(`Remove the agent for ${agent.device_name}? Its credential, metrics, and package inventory will be deleted. The Linux service must be uninstalled separately.`))return;setError("");try{await api.deleteAgent(agent.id,csrf);await refresh()}catch(reason){setError(reason instanceof Error?reason.message:"Unable to remove agent")}}
  async function details(agent:Agent){setSelected(agent);setPackageSearch("");const [history,inventory]=await Promise.all([api.agentMetrics(agent.id),api.agentPackages(agent.id)]);setMetrics(history);setPackages(inventory)}
  async function searchPackages(){if(selected)setPackages(await api.agentPackages(selected.id,packageSearch))}
  async function scanPackages(agent:Agent){setScanning(agent.id);setError("");setMessage("");try{const findings=await api.scanAgentPackages(agent.id,csrf);setMessage(`${agent.device_name}: package scan completed with ${findings.length} matched findings. Review Vulnerabilities and Action Center.`)}catch(reason){setError(reason instanceof Error?reason.message:"Package scan failed")}finally{setScanning("")}}
  async function copyCommand(){setError("");try{if(navigator.clipboard&&window.isSecureContext)await navigator.clipboard.writeText(command);else{const area=document.createElement("textarea");area.value=command;area.style.position="fixed";area.style.opacity="0";document.body.appendChild(area);area.select();const copied=document.execCommand("copy");area.remove();if(!copied)throw new Error()}setMessage("Command copied to clipboard.")}catch{setError("The browser blocked clipboard access. Select the command text and copy it manually.")}}

  return <>
    <header><div><p className="eyebrow">ENDPOINT TELEMETRY</p><h1>Agents</h1><p>Authenticated Linux agents report health, inventory, and approved remediation results.</p></div></header>
    <section className="panel agent-enroll"><div><h2>Connect a Linux system</h2><p>Select an existing device. Enrollment tokens are single-use and expire after 30 minutes.</p></div><select value={deviceId} onChange={event=>setDeviceId(event.target.value)}>{available.length===0?<option value="">No unenrolled devices</option>:available.map(device=><option key={device.id} value={device.id}>{device.display_name} · {device.address}</option>)}</select><button className="primary compact" onClick={()=>void enroll()} disabled={!deviceId}>Generate install command</button></section>
    {message&&<div className="notice panel">{message}</div>}{error&&<div className="error storage-error">{error}</div>}
    {agents.length===0?<div className="empty-state panel"><h2>No agents connected</h2><p>Add Linux servers to Devices first, then generate an enrollment command above.</p></div>:<div className="agent-grid">{agents.map(agent=><AgentCard key={agent.id} agent={agent} scanning={scanning} details={details} updateCommand={updateCommand} scanPackages={scanPackages} remove={remove}/>)}</div>}
    {command&&<div className="modal-backdrop"><div className="panel install-command"><div className="panel-title"><div><p className="eyebrow">{commandMode==="enroll"?"ONE-TIME ENROLLMENT":"AGENT + EXECUTOR UPDATE"}</p><h2>Run on the selected Linux system</h2></div><button className="close" onClick={()=>{setCommand("");void refresh()}}>×</button></div><p>{commandMode==="enroll"?"Review the downloaded scripts, then run these commands. The token expires in 30 minutes and cannot be shown again.":"This repairs agent v0.6.0 and executor v0.3.1 together, enables live playbook output, and restarts the service."}</p><pre>{command}</pre><button className="primary compact" onClick={()=>void copyCommand()}>Copy command</button></div></div>}
    {selected&&<AgentDetail agent={selected} metrics={metrics} packages={packages} packageSearch={packageSearch} setPackageSearch={setPackageSearch} searchPackages={searchPackages} close={()=>setSelected(null)}/>}
  </>;
}

function AgentCard({agent,scanning,details,updateCommand,scanPackages,remove}:{agent:Agent;scanning:string;details:(agent:Agent)=>Promise<void>;updateCommand:()=>void;scanPackages:(agent:Agent)=>Promise<void>;remove:(agent:Agent)=>Promise<void>}) {
  const current=agent.version==="0.6.0"&&agent.executor_version==="0.3.1";
  return <article className={`panel agent-card ${(agent.cpu_percent??0)>=85||(agent.memory_percent??0)>=85||(agent.disk_percent??0)>=90?"pressure":""}`}>
    <div className="panel-title"><div><p className="eyebrow">{agent.os_name?`${agent.os_name} ${agent.os_version||""}`:agent.platform}</p><h2><i className={`status-dot ${agent.connected?"online":"offline"}`}/>{agent.device_name}</h2><small>{agent.hostname||"Identity pending"}{agent.kernel_version&&` · kernel ${agent.kernel_version}`}</small><div className={`agent-version ${current?"current":"outdated"}`}><b>Agent v{agent.version} · Executor v{agent.executor_version||"missing"}</b><span>{current?"Current":"Repair required"}</span></div></div><div className="agent-card-actions"><span>{agent.connected?"Connected":"Disconnected"}</span><button onClick={()=>void details(agent)}>Details</button><button onClick={updateCommand}>{current?"Repair installation":"Update agent"}</button><button onClick={()=>void scanPackages(agent)} disabled={!agent.version.startsWith("0.")||scanning===agent.id}>{scanning===agent.id?"Scanning…":"Scan packages"}</button><button className="danger" onClick={()=>void remove(agent)}>Remove</button></div></div>
    <div className="agent-metrics"><div><small>CPU</small><b>{agent.cpu_percent??"—"}%</b></div><div><small>Memory</small><b>{agent.memory_percent??"—"}%</b></div><div><small>Disk</small><b>{agent.disk_percent??"—"}%</b></div><div><small>Disk free</small><b>{bytes(agent.disk_free_bytes)}</b></div><div><small>Uptime</small><b>{age(agent.uptime_seconds)}</b></div><div><small>Packages</small><b>{agent.package_count.toLocaleString()}</b></div><div><small>Containers</small><b>{agent.container_count.toLocaleString()}</b></div></div><small>Last heartbeat: {agent.last_heartbeat_at?new Date(agent.last_heartbeat_at).toLocaleString():"never"}</small>
  </article>;
}

function AgentDetail({agent,metrics,packages,packageSearch,setPackageSearch,searchPackages,close}:{agent:Agent;metrics:AgentMetric[];packages:InstalledPackage[];packageSearch:string;setPackageSearch:(value:string)=>void;searchPackages:()=>Promise<void>;close:()=>void}) {
  return <div className="modal-backdrop"><div className="panel agent-detail"><div className="panel-title"><div><p className="eyebrow">SYSTEM HEALTH</p><h2>{agent.device_name}</h2><p>{agent.hostname||"Unknown hostname"} · {agent.os_name||"Linux"} {agent.os_version||""} · {agent.kernel_version||"kernel pending"}</p></div><button className="close" onClick={close}>×</button></div><h3>Recent metric history</h3>{metrics.length===0?<p className="quiet">Waiting for metric history.</p>:<div className="metric-history"><MetricBars label="CPU" values={metrics.map(item=>item.cpu_percent)}/><MetricBars label="Memory" values={metrics.map(item=>item.memory_percent)}/><MetricBars label="Disk" values={metrics.map(item=>item.disk_percent)}/></div>}<div className="package-heading"><div><h3>Installed packages</h3><small>Up to 500 matches are shown.</small></div><div><input value={packageSearch} onChange={event=>setPackageSearch(event.target.value)} placeholder="Search packages"/><button onClick={()=>void searchPackages()}>Search</button></div></div><div className="package-list"><div className="package-row heading"><span>Name / source</span><span>Installed / source version</span><span>Architecture</span></div>{packages.map(item=><div className="package-row" key={`${item.name}-${item.architecture}`}><b>{item.name}<small>{item.source_name&&item.source_name!==item.name?item.source_name:""}</small></b><span>{item.version}<small>{item.source_version&&item.source_version!==item.version?item.source_version:""}</small></span><span>{item.architecture||"—"}</span></div>)}</div></div></div>;
}

function MetricBars({label,values}:{label:string;values:number[]}){const recent=values.slice(-60),average=recent.reduce((sum,value)=>sum+value,0)/recent.length;return <div><div><b>{label}</b><span>Avg {average.toFixed(0)}% · Max {Math.max(...recent)}%</span></div><div className="metric-bars">{recent.map((value,index)=><i key={index} style={{height:`${Math.max(value,2)}%`}} title={`${value}%`}/>)}</div></div>}
