import { FormEvent, useState } from "react";
import { api, ApplicationIntegration } from "./api";

const labels:Record<string,[string,string,string,string]>={sonarr:["Queue","Failed","Series","Monitored"],radarr:["Queue","Failed","Movies","Monitored"],prowlarr:["Disabled","Health","Indexers","Enabled"],sabnzbd:["Queue","Failed","History","Active"],plex:["Queue","Failures","Libraries","Streams"],qbittorrent:["Torrents","Errors","Torrents","Active"]};

export function ApplicationsPage({items,csrf,refresh}:{items:ApplicationIntegration[];csrf:string;refresh:()=>Promise<void>}){
 const [adding,setAdding]=useState(false),[busy,setBusy]=useState(""),[error,setError]=useState(""),[kind,setKind]=useState("sonarr");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy("create");setError("");const data=new FormData(e.currentTarget);try{await api.createApplication({name:data.get("name"),kind,base_url:data.get("url"),api_key:data.get("key"),username:data.get("username")||null},csrf);setAdding(false);await refresh()}catch(x){setError(x instanceof Error?x.message:"Could not connect application")}finally{setBusy("")}}
 const size=(value:number|null)=>value===null?"No disk data":value>1e9?`${(value/1e9).toFixed(1)} GB free`:`${(value/1e6).toFixed(1)} MB free`;
 return <><header><div><p className="eyebrow">NATIVE APPLICATION DATA</p><h1>Application insights</h1><p>Queues, failures, libraries, sessions, indexers, torrents, and historical activity.</p></div><button className="primary compact" onClick={()=>setAdding(true)}>Connect application</button></header>{error&&!adding&&<div className="error storage-error">{error}</div>}{items.length===0?<div className="empty-state panel"><h2>No native applications connected</h2><p>Connect a supported application to begin collecting operational snapshots.</p></div>:<div className="application-grid">{items.map(item=>{const latest=item.latest,max=Math.max(1,...item.history.map(x=>x.queue_count)),metricLabels=labels[item.kind];return <article className="panel application-card" key={item.id}><div className="panel-title"><div><p className="eyebrow">{item.kind.toUpperCase()}</p><h2>{item.name}</h2><small>{item.base_url}</small></div><span className={`tag ${item.last_sync_status==="healthy"?"":"warning"}`}>{item.last_sync_status}</span></div>{latest?<><div className="application-metrics"><Metric label={metricLabels[0]} value={latest.queue_count}/><Metric label={metricLabels[1]} value={latest.failed_count} danger={latest.failed_count>0}/><Metric label={metricLabels[2]} value={latest.item_count}/><Metric label={metricLabels[3]} value={latest.active_count}/></div><div className="application-meta"><span>Version <b>{latest.version||"unknown"}</b></span><span>{size(latest.disk_free_bytes)}</span><span>Updated {new Date(latest.collected_at).toLocaleString()}</span></div><div className="sparkline">{item.history.slice(-60).map((point,index)=><i key={`${point.collected_at}-${index}`} style={{height:`${Math.max(3,point.queue_count*100/max)}%`}}/>)}</div></>:<p className="quiet">No snapshot collected yet.</p>}{item.last_sync_error&&<div className="error">{item.last_sync_error}</div>}<div className="row-actions"><button disabled={busy===item.id} onClick={async()=>{setBusy(item.id);try{await api.syncApplication(item.id,csrf);await refresh()}finally{setBusy("")}}}>{busy===item.id?"Syncing…":"Sync now"}</button><button className="danger" onClick={async()=>{if(confirm(`Disconnect ${item.name}?`)){await api.deleteApplication(item.id,csrf);await refresh()}}}>Disconnect</button></div></article>})}</div>}
 {adding&&<div className="modal-backdrop"><form className="device-form panel application-modal" onSubmit={submit}><div className="panel-title"><div><p className="eyebrow">READ-ONLY API</p><h2>Connect application</h2></div><button type="button" className="close" onClick={()=>setAdding(false)}>×</button></div><p>The target must be private/local. Credentials are encrypted and never returned to the browser.</p><label>Application<select value={kind} onChange={e=>setKind(e.target.value)}><option value="sonarr">Sonarr</option><option value="radarr">Radarr</option><option value="prowlarr">Prowlarr</option><option value="sabnzbd">SABnzbd</option><option value="plex">Plex</option><option value="qbittorrent">qBittorrent</option></select></label><label>Display name<input name="name" required placeholder="Media server"/></label><label>Local base URL<input name="url" type="url" required placeholder="http://10.0.0.230:8989"/></label>{kind==="qbittorrent"&&<label>Username<input name="username" required defaultValue="admin" autoComplete="username"/></label>}<label>{kind==="qbittorrent"?"Password":kind==="plex"?"Plex token":"API key"}<input name="key" type="password" required autoComplete="off"/></label>{error&&<div className="error">{error}</div>}<div className="form-actions"><button type="button" onClick={()=>setAdding(false)}>Cancel</button><button className="primary compact" disabled={busy==="create"}>{busy==="create"?"Connecting…":"Connect and sync"}</button></div></form></div>}</>;
}
function Metric({label,value,danger}:{label:string;value:number;danger?:boolean}){return <div><small>{label}</small><b className={danger?"report-danger":""}>{value}</b></div>}
