import { FormEvent, useState } from "react";
import { api, ApplicationIntegration } from "./api";

export function ApplicationsPage({items,csrf,refresh}:{items:ApplicationIntegration[];csrf:string;refresh:()=>Promise<void>}){
 const [adding,setAdding]=useState(false),[busy,setBusy]=useState(""),[error,setError]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy("create");setError("");const data=new FormData(e.currentTarget);try{await api.createApplication({name:data.get("name"),kind:data.get("kind"),base_url:data.get("url"),api_key:data.get("key")},csrf);setAdding(false);await refresh()}catch(x){setError(x instanceof Error?x.message:"Could not connect application")}finally{setBusy("")}}
 const size=(value:number|null)=>value===null?"No disk data":value>1e9?`${(value/1e9).toFixed(1)} GB free`:`${(value/1e6).toFixed(1)} MB free`;
 return <><header><div><p className="eyebrow">NATIVE APPLICATION DATA</p><h1>Application insights</h1><p>Read-only operational metrics from the APIs behind your monitored apps.</p></div><button className="primary compact" onClick={()=>setAdding(true)}>Connect application</button></header>{error&&!adding&&<div className="error storage-error">{error}</div>}{items.length===0?<div className="empty-state panel"><div>＋</div><h2>No native applications connected</h2><p>Connect Sonarr, Radarr, or SABnzbd to see queues, failures, library counts, activity, versions, and history.</p></div>:<div className="application-grid">{items.map(item=>{const latest=item.latest,max=Math.max(1,...item.history.map(x=>x.queue_count));return <article className="panel application-card" key={item.id}><div className="panel-title"><div><p className="eyebrow">{item.kind.toUpperCase()}</p><h2>{item.name}</h2><small>{item.base_url}</small></div><span className={`tag ${item.last_sync_status==="healthy"?"":"warning"}`}>{item.last_sync_status}</span></div>{latest?<><div className="application-metrics"><Metric label="Queue" value={latest.queue_count}/><Metric label="Failed" value={latest.failed_count} danger={latest.failed_count>0}/><Metric label={item.kind==="sabnzbd"?"History":"Library"} value={latest.item_count}/><Metric label="Active" value={latest.active_count}/></div><div className="application-meta"><span>Version <b>{latest.version||"unknown"}</b></span><span>{size(latest.disk_free_bytes)}</span><span>Updated {new Date(latest.collected_at).toLocaleString()}</span></div><div className="sparkline" title="Queue depth over the last 7 days">{item.history.slice(-60).map((point,index)=><i key={`${point.collected_at}-${index}`} style={{height:`${Math.max(3,point.queue_count*100/max)}%`}}/>)}</div></>:<div className="empty-state compact"><p>No snapshot collected yet.</p></div>}{item.last_sync_error&&<div className="error">{item.last_sync_error}</div>}<div className="row-actions"><button disabled={busy===item.id} onClick={async()=>{setBusy(item.id);try{await api.syncApplication(item.id,csrf);await refresh()}finally{setBusy("")}}}>{busy===item.id?"Syncing…":"Sync now"}</button><button className="danger" onClick={async()=>{if(confirm(`Disconnect ${item.name}?`)){await api.deleteApplication(item.id,csrf);await refresh()}}}>Disconnect</button></div></article>})}</div>}
 {adding&&<div className="modal-backdrop"><form className="device-form panel application-modal" onSubmit={submit}><div className="panel-title"><div><p className="eyebrow">READ-ONLY API</p><h2>Connect application</h2></div><button type="button" className="close" onClick={()=>setAdding(false)}>×</button></div><p>The URL must resolve to a private or local address. The API key is encrypted at rest and never returned to the browser.</p><label>Application<select name="kind"><option value="sonarr">Sonarr</option><option value="radarr">Radarr</option><option value="sabnzbd">SABnzbd</option></select></label><label>Display name<input name="name" required placeholder="Living Room Sonarr"/></label><label>Local base URL<input name="url" type="url" required placeholder="http://10.0.0.230:8989"/></label><label>API key<input name="key" type="password" required autoComplete="off"/></label>{error&&<div className="error">{error}</div>}<div className="form-actions"><button type="button" onClick={()=>setAdding(false)}>Cancel</button><button className="primary compact" disabled={busy==="create"}>{busy==="create"?"Connecting…":"Connect and sync"}</button></div></form></div>}</>;
}
function Metric({label,value,danger}:{label:string;value:number;danger?:boolean}){return <div><small>{label}</small><b className={danger?"report-danger":""}>{value}</b></div>}
