import { useEffect, useMemo, useState } from "react";
import { api, ContainerEvent, ContainerInstance } from "./api";

export function ContainersPage({containers,refresh,csrf}:{containers:ContainerInstance[];refresh:()=>Promise<void>;csrf?:string}) {
  const [section,setSection]=useState<"inventory"|"alerts">("inventory"),[events,setEvents]=useState<ContainerEvent[]>([]),[search,setSearch]=useState(""),[device,setDevice]=useState("all"),[state,setState]=useState("all"),[selected,setSelected]=useState<ContainerInstance|null>(null),[busy,setBusy]=useState("");
  async function loadEvents(){setEvents(await api.containerEvents())} useEffect(()=>{void loadEvents()},[]);
  const devices=[...new Set(containers.map(item=>item.device_name))].sort();
  const visible=useMemo(()=>containers.filter(item=>(!search||`${item.name} ${item.image}`.toLowerCase().includes(search.toLowerCase()))&&(device==="all"||item.device_name===device)&&(state==="all"||(state==="unhealthy"?item.health==="unhealthy":state==="missing"?!item.present:item.state===state))),[containers,search,device,state]);
  const running=containers.filter(item=>item.state==="running").length,unhealthy=containers.filter(item=>item.health==="unhealthy").length,stopped=containers.filter(item=>item.state!=="running").length,openEvents=events.filter(item=>!item.acknowledged_at).length;
  async function acknowledge(id:string){setBusy(id);try{const token=csrf||(await api.csrf()).csrf_token;await api.acknowledgeContainerEvent(id,token);await loadEvents()}finally{setBusy("")}}
  return <><div className="network-tabs panel"><button className={section==="inventory"?"active":""} onClick={()=>setSection("inventory")}>Inventory</button><button className={section==="alerts"?"active":""} onClick={()=>{setSection("alerts");void loadEvents()}}>Alerts{openEvents?` (${openEvents})`:""}</button></div><header><div><p className="eyebrow">DOCKER VISIBILITY</p><h1>{section==="inventory"?"Containers":"Container alerts"}</h1><p>{section==="inventory"?"Runtime health and lifecycle details reported securely by your Linux agents.":"Restarts, health failures, stopped containers, image changes, and disappearances."}</p></div><button onClick={()=>void (section==="inventory"?refresh():loadEvents())}>Refresh</button></header>
  {section==="alerts"?<ContainerAlerts events={events} busy={busy} acknowledge={acknowledge}/>:<><section className="status-grid container-summary"><Status label="Total" value={containers.length}/><Status label="Running" value={running} tone="green"/><Status label="Unhealthy" value={unhealthy} tone={unhealthy?"red":"green"}/><Status label="Stopped / missing" value={stopped} tone={stopped?"amber":undefined}/></section><section className="panel"><div className="filter-row"><input placeholder="Search name or image" value={search} onChange={e=>setSearch(e.target.value)}/><select value={device} onChange={e=>setDevice(e.target.value)}><option value="all">All devices</option>{devices.map(name=><option key={name}>{name}</option>)}</select><select value={state} onChange={e=>setState(e.target.value)}><option value="all">All states</option><option value="running">Running</option><option value="exited">Exited</option><option value="paused">Paused</option><option value="unhealthy">Unhealthy</option><option value="missing">Missing</option></select></div>{!containers.length?<div className="empty-state"><h2>No container inventory yet</h2><p>Install or update the Linux agent; Docker inventory appears automatically.</p></div>:!visible.length?<div className="empty-state"><h2>No matching containers</h2></div>:<div className="container-list">{visible.map(item=><article className="container-row clickable" key={item.id} onClick={()=>setSelected(item)}><div className={`container-state ${item.health==="unhealthy"||item.state!=="running"?"bad":"good"}`}/><div className="container-identity"><strong>{item.name}</strong><small>{item.image}</small></div><div><small>Host</small><b>{item.device_name}</b><span>{item.hostname}</span></div><div><small>Runtime</small><b>{item.state}{item.health?` · ${item.health}`:""}</b><span>{item.status||"No runtime detail"}</span></div><div><small>Ports</small><b>{item.ports||"None published"}</b><span>{item.restart_count} restarts</span></div>{(item.stale||!item.present)&&<span className="tag warning">{!item.present?"Missing":"Stale"}</span>}</article>)}</div>}</section></>}
  {selected&&<div className="modal-backdrop" onMouseDown={()=>setSelected(null)}><div className="panel container-detail-modal" onMouseDown={e=>e.stopPropagation()}><div className="panel-title"><div><p className="eyebrow">CONTAINER DETAIL</p><h2>{selected.name}</h2></div><button className="close" onClick={()=>setSelected(null)}>×</button></div><div className="container-detail-grid"><Detail label="Host" value={`${selected.device_name} · ${selected.hostname||"unknown hostname"}`}/><Detail label="Runtime" value={`${selected.state}${selected.health?` · ${selected.health}`:""}`}/><Detail label="Image" value={selected.image}/><Detail label="Container ID" value={selected.container_id}/><Detail label="Published ports" value={selected.ports||"None"}/><Detail label="Restart count" value={String(selected.restart_count)}/><Detail label="Last observed" value={new Date(selected.observed_at).toLocaleString()}/><Detail label="Status detail" value={selected.status||"None"}/></div><h3>Recent activity</h3><div className="mini-event-list">{events.filter(e=>e.container_id===selected.container_id&&e.agent_id===selected.agent_id).slice(0,10).map(e=><div key={e.id}><i className={`alert-severity ${e.severity}`}/><span><b>{e.kind.replaceAll("_"," ")}</b><small>{e.message}</small></span><time>{new Date(e.occurred_at).toLocaleString()}</time></div>)}{!events.some(e=>e.container_id===selected.container_id&&e.agent_id===selected.agent_id)&&<p className="quiet">No lifecycle changes recorded yet.</p>}</div></div></div>}</>;
}
function ContainerAlerts({events,busy,acknowledge}:{events:ContainerEvent[];busy:string;acknowledge:(id:string)=>Promise<void>}){const [filter,setFilter]=useState("open");const visible=events.filter(e=>filter==="all"||filter==="open"&&!e.acknowledged_at||filter==="acknowledged"&&e.acknowledged_at);return <><div className="panel filter-row"><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="open">Needs review</option><option value="all">All events</option><option value="acknowledged">Acknowledged</option></select><b>{visible.length} shown</b></div>{visible.length===0?<div className="empty-state panel"><div>✓</div><h2>No container alerts need review</h2></div>:<div className="panel network-alert-list">{visible.map(e=><article key={e.id} className={e.acknowledged_at?"acknowledged":""}><i className={`alert-severity ${e.severity}`}/><div><p className="eyebrow">{e.kind.replaceAll("_"," ").toUpperCase()} · {e.severity.toUpperCase()}</p><h2>{e.container_name}</h2><p>{e.message} Host: {e.device_name}.</p></div><time>{new Date(e.occurred_at).toLocaleString()}</time>{e.acknowledged_at?<span className="tag">Reviewed</span>:<button disabled={busy===e.id} onClick={()=>void acknowledge(e.id)}>{busy===e.id?"Saving…":"Acknowledge"}</button>}</article>)}</div>}</>}
function Detail({label,value}:{label:string;value:string}){return <div><small>{label}</small><b>{value}</b></div>}
function Status({label,value,tone}:{label:string;value:number;tone?:string}){return <article className="status-card"><p>{label}</p><strong className={tone}>{value}</strong><small>reported containers</small></article>}
