import { FormEvent, useState } from "react";
import { api, Device, DuplicateCandidate } from "./api";

export function DevicesPage({ devices, csrf, refresh }: { devices: Device[]; csrf: string; refresh: () => Promise<void> }) {
  const [adding, setAdding] = useState(false); const [editing, setEditing] = useState<Device | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const [reviewing,setReviewing]=useState(false);const [candidates,setCandidates]=useState<DuplicateCandidate[]>([]);
  function closeForm(){setAdding(false);setEditing(null);setError("")}
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError("");
    const data = new FormData(event.currentTarget);
    try {
      const payload={display_name:data.get("name"),address:data.get("address"),hostname:data.get("hostname")||null,device_type:data.get("type")||null,criticality:data.get("criticality"),trust:data.get("trust"),monitor_port:Number(data.get("port")),notes:data.get("notes")||null};
      if(editing) await api.updateDevice(editing.id,payload,csrf); else await api.createDevice(payload,csrf);
      closeForm(); await refresh();
    } catch(reason) { setError(reason instanceof Error ? reason.message : "Could not add device"); }
    finally { setBusy(false); }
  }
  async function toggleNotifications(device:Device){setError("");try{await api.toggleDeviceNotifications(device.id,!device.notifications_muted,csrf);await refresh()}catch(reason){setError(reason instanceof Error?reason.message:"Could not update notification mute")}}
  async function reviewDuplicates(){setBusy(true);setError("");try{setCandidates(await api.duplicateDevices());setReviewing(true)}catch(reason){setError(reason instanceof Error?reason.message:"Could not check identities")}finally{setBusy(false)}}
  async function merge(target:Device,source:Device){if(!confirm(`Merge ${source.display_name} into ${target.display_name}? The ${target.display_name} record will be kept.`))return;setBusy(true);setError("");try{await api.mergeDevice(target.id,source.id,csrf);setCandidates(await api.duplicateDevices());await refresh()}catch(reason){setError(reason instanceof Error?reason.message:"Could not merge devices")}finally{setBusy(false)}}
  return <>
    <header><div><p className="eyebrow">INVENTORY</p><h1>Devices</h1><p>Add the systems you want Sentinel to watch every 30 seconds.</p></div><div className="row-actions"><button onClick={()=>void reviewDuplicates()} disabled={busy}>Review duplicates</button><button className="primary compact" onClick={()=>setAdding(true)}>+ Add device</button></div></header>
    {reviewing&&<div className="modal-backdrop"><div className="panel duplicate-modal"><div className="panel-title"><div><p className="eyebrow">IDENTITY CLEANUP</p><h2>Possible duplicate devices</h2></div><button className="close" onClick={()=>setReviewing(false)}>×</button></div><p>Sentinel compares names, hostnames, IPs, and MAC addresses. You choose which record survives.</p>{error&&<div className="error">{error}</div>}{candidates.length===0?<div className="empty-state"><div>✓</div><h2>No likely duplicates</h2><p>Your current canonical device list looks clean.</p></div>:<div className="duplicate-list">{candidates.map(item=><article key={`${item.left.id}-${item.right.id}`}><div className="duplicate-confidence"><b>{item.confidence}%</b><small>match</small></div><div><b>{item.left.display_name}</b><small>{item.left.address} · {item.left.hostname||"no hostname"}</small></div><span>⇄</span><div><b>{item.right.display_name}</b><small>{item.right.address} · {item.right.hostname||"no hostname"}</small></div><div className="duplicate-reasons">{item.reasons.map(reason=><i key={reason}>{reason}</i>)}</div><div className="row-actions"><button disabled={busy} onClick={()=>void merge(item.left,item.right)}>Keep {item.left.display_name}</button><button disabled={busy} onClick={()=>void merge(item.right,item.left)}>Keep {item.right.display_name}</button></div></article>)}</div>}</div></div>}
    {(adding||editing) && <div className="modal-backdrop"><form className="device-form panel" onSubmit={submit}><div className="panel-title"><div><p className="eyebrow">{editing?"EDIT DEVICE":"NEW DEVICE"}</p><h2>{editing?"Update monitoring":"Start monitoring"}</h2></div><button type="button" className="close" onClick={closeForm}>×</button></div><p>Sentinel performs a safe TCP connection check. It does not scan ports or change the device.</p><label>Display name<input name="name" required placeholder="Home Assistant" defaultValue={editing?.display_name}/></label><label>IP address or local hostname<input name="address" required placeholder="192.168.1.50" defaultValue={editing?.address}/></label><label>Hostname (optional)<input name="hostname" placeholder="homeassistant.local" defaultValue={editing?.hostname??""}/></label><div className="form-row"><label>Device type<select name="type" defaultValue={editing?.device_type??"server"}><option value="server">Server</option><option value="workstation">Workstation</option><option value="raspberry-pi">Raspberry Pi</option><option value="home-assistant">Home Assistant</option><option value="iot">IoT</option></select></label><label>TCP port<input name="port" type="number" min="1" max="65535" defaultValue={editing?.monitor_port??443} required /></label></div><div className="form-row"><label>Criticality<select name="criticality" defaultValue={editing?.criticality??"normal"}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="critical">Critical</option></select></label><label>Trust<select name="trust" defaultValue={editing?.trust??"trusted"}><option value="trusted">Trusted</option><option value="unknown">Unknown</option><option value="guest">Guest</option><option value="ignored">Ignored</option></select></label></div><label>Notes<textarea name="notes" rows={3} defaultValue={editing?.notes??""} placeholder="Purpose, location, or anything useful…"/></label>{error&&<div className="error">{error}</div>}<div className="form-actions"><button type="button" onClick={closeForm}>Cancel</button><button className="primary compact" disabled={busy}>{busy?"Checking…":editing?"Save and check":"Add and check"}</button></div></form></div>}
    {error&&!adding&&!editing&&<div className="error storage-error">{error}</div>}{devices.length===0 ? <div className="empty-state panel"><div>＋</div><h2>No devices yet</h2><p>Add a server, Raspberry Pi, workstation, Home Assistant host, or other LAN device.</p><button className="primary compact" onClick={()=>setAdding(true)}>Add your first device</button></div> : <div className="device-list panel"><div className="device-row heading"><span>Device</span><span>Target</span><span>Status</span><span>Latency</span><span></span></div>{devices.map(device=><div className="device-row" key={device.id}><span><b>{device.display_name}</b><small>{device.device_type??"Device"}</small></span><span>{device.address}:{device.monitor_port}</span><span><i className={`status-dot ${device.status}`}/>{device.status}</span><span>{device.last_latency_ms ? `${device.last_latency_ms} ms` : "—"}</span><div className="row-actions"><MuteToggle muted={device.notifications_muted} onToggle={()=>void toggleNotifications(device)}/><button onClick={()=>setEditing(device)}>Edit</button><button onClick={async()=>{await api.checkDevice(device.id,csrf);await refresh();}}>Check</button></div></div>)}</div>}
  </>;
}

function MuteToggle({muted,onToggle}:{muted:boolean;onToggle:()=>void}){return <button className={`mute-toggle ${muted?"muted":""}`} aria-pressed={muted} title={muted?"Notifications muted — click to unmute":"Notifications on — click to mute"} onClick={onToggle}><span>{muted?"🔕":"🔔"}</span><i/><b>{muted?"Muted":"Alerts"}</b></button>}
