import { useEffect, useMemo, useState } from "react";
import { api, Device, Notification } from "./api";

export function NotificationsPage({notifications,csrf,refresh}:{notifications:Notification[];csrf:string;refresh:()=>Promise<void>}){
  const [busy,setBusy]=useState(""),[message,setMessage]=useState(""),[selected,setSelected]=useState<Set<string>>(new Set());
  const [devices,setDevices]=useState<Device[]>([]),[deviceId,setDeviceId]=useState(""),[minutes,setMinutes]=useState(60),[reason,setReason]=useState("Testing / maintenance");
  useEffect(()=>{void api.devices().then(items=>{setDevices(items);setDeviceId(current=>current||items[0]?.id||"")})},[]);
  const muted=useMemo(()=>devices.filter(device=>device.alerts_muted_until&&new Date(device.alerts_muted_until)>new Date()),[devices]);

  async function test(){setBusy("test");setMessage("");try{const result=await api.testNotification(csrf);setMessage(result.status==="sent"?"Test email sent successfully.":result.error||`Test email ${result.status}.`);await refresh()}catch(error){setMessage(error instanceof Error?error.message:"Test failed")}finally{setBusy("")}}
  async function dismiss(){if(!selected.size)return;setBusy("dismiss");try{await api.dismissNotifications([...selected],csrf);setSelected(new Set());setMessage(`${selected.size} notifications dismissed.`);await refresh()}catch(error){setMessage(error instanceof Error?error.message:"Unable to dismiss notifications")}finally{setBusy("")}}
  async function mute(){if(!deviceId)return;setBusy("mute");try{const result=await api.muteDeviceAlerts(deviceId,minutes,reason,csrf);setDevices(current=>current.map(device=>device.id===deviceId?{...device,alerts_muted_until:result.alerts_muted_until,alert_mute_reason:result.alert_mute_reason}:device));setMessage(minutes?`Alerts muted until ${new Date(result.alerts_muted_until!).toLocaleString()}.`:"Alerts unmuted.")}catch(error){setMessage(error instanceof Error?error.message:"Unable to update alert mute")}finally{setBusy("")}}
  async function unmute(device:Device){setBusy(device.id);try{await api.muteDeviceAlerts(device.id,0,"",csrf);setDevices(current=>current.map(item=>item.id===device.id?{...item,alerts_muted_until:null,alert_mute_reason:null}:item));setMessage(`${device.display_name} alerts unmuted.`)}catch(error){setMessage(error instanceof Error?error.message:"Unable to unmute alerts")}finally{setBusy("")}}
  function toggle(id:string){setSelected(current=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next})}

  return <>
    <header><div><p className="eyebrow">DELIVERY AND SUPPRESSION</p><h1>Notifications</h1><p>Review delivery history, dismiss records, and pause alerts during testing or maintenance.</p></div><button className="primary compact" disabled={!!busy} onClick={()=>void test()}>{busy==="test"?"Sending…":"Send test email"}</button></header>
    {message&&<div className="notice panel">{message}</div>}
    <section className="panel mute-controls"><div><h2>Mute a device</h2><p>Monitoring continues and incidents are still recorded; only email delivery is suppressed.</p></div><label>Device<select value={deviceId} onChange={event=>setDeviceId(event.target.value)}>{devices.map(device=><option value={device.id} key={device.id}>{device.display_name}</option>)}</select></label><label>Duration<select value={minutes} onChange={event=>setMinutes(Number(event.target.value))}><option value={30}>30 minutes</option><option value={60}>1 hour</option><option value={240}>4 hours</option><option value={1440}>24 hours</option><option value={10080}>7 days</option></select></label><label>Reason<input value={reason} onChange={event=>setReason(event.target.value)} maxLength={300}/></label><button className="primary compact" disabled={!deviceId||busy==="mute"} onClick={()=>void mute()}>Mute alerts</button></section>
    {muted.length>0&&<section className="muted-devices">{muted.map(device=><article className="panel" key={device.id}><div><b>{device.display_name}</b><span>Muted until {new Date(device.alerts_muted_until!).toLocaleString()}</span><small>{device.alert_mute_reason}</small></div><button onClick={()=>void unmute(device)} disabled={busy===device.id}>Unmute</button></article>)}</section>}
    <div className="panel notification-bulk"><div><b>{selected.size} selected</b><span>Select delivery records to clear them from this view.</span></div><button onClick={()=>setSelected(new Set(notifications.map(item=>item.id)))} disabled={!notifications.length}>Select all</button><button onClick={()=>setSelected(new Set())} disabled={!selected.size}>Clear</button><button className="danger" onClick={()=>void dismiss()} disabled={!selected.size||busy==="dismiss"}>{busy==="dismiss"?"Dismissing…":`Dismiss selected (${selected.size})`}</button></div>
    {notifications.length===0?<div className="empty-state panel"><div>✉</div><h2>No notifications yet</h2><p>Send a test email or wait for a future outage transition.</p></div>:<div className="device-list panel"><div className="notification-row selectable heading"><span></span><span>Notification</span><span>Recipient</span><span>Status</span><span>Time</span></div>{notifications.map(item=><label className={`notification-row selectable ${selected.has(item.id)?"selected":""}`} key={item.id}><input type="checkbox" checked={selected.has(item.id)} onChange={()=>toggle(item.id)}/><span><b>{item.subject}</b><small>{item.kind}</small></span><span>{item.recipient||"Not configured"}</span><span title={item.error||""}><i className={`status-dot ${item.status==="sent"?"up":item.status==="failed"?"down":"paused"}`}/>{item.status}<small>{item.error}</small></span><span>{new Date(item.created_at).toLocaleString()}</span></label>)}</div>}
  </>;
}
