import { OverviewReport } from "./api";

const percent=(value:number|null)=>value===null?"No data":`${value.toFixed(2)}%`;
const size=(bytes:number)=>bytes>=1_073_741_824?`${(bytes/1_073_741_824).toFixed(1)} GB`:`${(bytes/1_048_576).toFixed(1)} MB`;

export function ReportsPage({report,refresh}:{report:OverviewReport|null;refresh:()=>Promise<void>}) {
  if(!report)return <><header><div><p className="eyebrow">OBSERVABILITY SUMMARY</p><h1>Reports</h1><p>Loading collected monitoring data…</p></div></header></>;
  const vulnerabilities=Object.entries(report.active_vulnerabilities).sort(([a],[b])=>a.localeCompare(b));
  return <><header><div><p className="eyebrow">OBSERVABILITY SUMMARY</p><h1>Reports</h1><p>Real measurements from Sentinel’s checks and findings, generated {new Date(report.generated_at).toLocaleString()}.</p></div><button className="primary compact" onClick={()=>void refresh()}>Refresh report</button></header><section className="status-grid report-cards"><article className="status-card"><p>24-hour uptime</p><strong>{percent(report.last_24_hours.uptime_percent)}</strong><small>{report.last_24_hours.checks.toLocaleString()} checks · {report.last_24_hours.average_response_ms??"—"} ms average</small></article><article className="status-card"><p>7-day uptime</p><strong>{percent(report.last_7_days.uptime_percent)}</strong><small>{report.last_7_days.checks.toLocaleString()} checks recorded</small></article><article className="status-card"><p>Open incidents</p><strong>{report.open_incidents}</strong><small>{report.incidents_7_days} started in 7 days</small></article><article className="status-card"><p>Known exploited</p><strong className={report.known_exploited?"report-danger":"green"}>{report.known_exploited}</strong><small>Active CISA KEV findings</small></article></section><section className="report-grid"><article className="panel"><p className="eyebrow">SERVICE RELIABILITY · 24 HOURS</p><h2>Uptime by service</h2>{report.services.length===0?<p className="quiet">Create service monitors to begin collecting uptime.</p>:<div className="service-report">{report.services.map(service=><div key={service.id}><div><b><i className={`status-dot ${service.status}`}/>{service.name}</b><span>{percent(service.uptime_percent)}</span></div><div className="uptime-track"><i style={{width:`${service.uptime_percent??0}%`}}/></div><small>{service.checks} checks · {service.average_response_ms??"—"} ms average</small></div>)}</div>}</article><article className="panel"><p className="eyebrow">SECURITY AND CAPACITY</p><h2>Attention summary</h2><ul className="report-list"><li><span>Network changes, 7 days</span><b>{report.network_changes_7_days}</b></li>{vulnerabilities.map(([severity,count])=><li key={severity}><span>{severity} vulnerabilities</span><b>{count}</b></li>)}<li><span>Storage recommendations</span><b>{report.storage_recommendations}</b></li><li><span>Flagged storage</span><b>{size(report.storage_flagged_bytes)}</b></li></ul><p className="quiet">Flagged storage is not automatically recoverable space. Review every recommendation before acting.</p></article></section></>;
}
