import { useEffect, useState } from "react";
import { api, HistoricalReport, OverviewReport } from "./api";

const percent=(value:number|null)=>value===null?"No data":`${value.toFixed(2)}%`;
const size=(bytes:number)=>bytes>=1_073_741_824?`${(bytes/1_073_741_824).toFixed(1)} GB`:`${(bytes/1_048_576).toFixed(1)} MB`;

export function ReportsPage({report,refresh}:{report:OverviewReport|null;refresh:()=>Promise<void>}) {
  const [days,setDays]=useState(30),[history,setHistory]=useState<HistoricalReport|null>(null),[busy,setBusy]=useState(false);
  async function load(range=days){setBusy(true);try{setHistory(await api.historicalReport(range))}finally{setBusy(false)}}
  useEffect(()=>{void load(days)},[]);
  if(!report)return <header><div><p className="eyebrow">OBSERVABILITY SUMMARY</p><h1>Reports</h1><p>Loading collected monitoring data…</p></div></header>;
  const vulnerabilities=Object.entries(report.active_vulnerabilities).sort(([a],[b])=>a.localeCompare(b));
  const remediation=Object.entries(report.remediation_status).filter(([status])=>status!=="archived").sort(([a],[b])=>a.localeCompare(b));
  return <><header><div><p className="eyebrow">OPERATIONS AND SECURITY</p><h1>Reports</h1><p>Reliability, changes, and risk over time—not only the current snapshot.</p></div><div className="report-actions"><select value={days} onChange={e=>{const value=Number(e.target.value);setDays(value);void load(value)}}><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option></select><a className="button-link" href={`/api/v1/reports/history.csv?days=${days}`}>Export CSV</a><button onClick={()=>{void refresh();void load()}} disabled={busy}>{busy?"Loading…":"Refresh"}</button></div></header>
  <section className="status-grid report-cards"><article className="status-card"><p>{days}-day uptime</p><strong>{percent(history?.summary.uptime_percent??null)}</strong><small>{history?.summary.checks.toLocaleString()??0} checks · {history?.summary.average_response_ms??"—"} ms average</small></article><article className="status-card"><p>Incidents</p><strong>{history?.incidents??0}</strong><small>{history?.expected_incidents??0} expected maintenance events</small></article><article className="status-card"><p>Network changes</p><strong>{history?.network_changes??0}</strong><small>Observed port changes</small></article><article className="status-card"><p>Container alerts</p><strong>{history?.container_alerts??0}</strong><small>Lifecycle and health changes</small></article></section>
  {history&&<section className="panel report-section"><div className="panel-title"><div><p className="eyebrow">DAILY TREND · {days} DAYS</p><h2>Reliability and operational changes</h2></div><span>{new Date(history.start_at).toLocaleDateString()} – {new Date(history.end_at).toLocaleDateString()}</span></div><TrendChart history={history}/></section>}
  <section className="report-grid"><article className="panel"><p className="eyebrow">SERVICE RELIABILITY · {days} DAYS</p><h2>Uptime by service</h2>{!history?.services.length?<p className="quiet">Create service monitors to begin collecting uptime.</p>:<div className="service-report">{history.services.map(service=><div key={service.id}><div><b><i className={`status-dot ${service.status}`}/>{service.name}</b><span>{percent(service.uptime_percent)}</span></div><div className="uptime-track"><i style={{width:`${service.uptime_percent??0}%`}}/></div><small>{service.checks} checks · {service.average_response_ms??"—"} ms average</small></div>)}</div>}</article><article className="panel"><p className="eyebrow">SECURITY AND CAPACITY</p><h2>Current attention summary</h2><ul className="report-list"><li><span>Open incidents</span><b>{report.open_incidents}</b></li>{vulnerabilities.map(([severity,count])=><li key={severity}><span>{severity} vulnerabilities</span><b>{count}</b></li>)}<li><span>Known exploited</span><b>{report.known_exploited}</b></li><li><span>Storage recommendations</span><b>{report.storage_recommendations}</b></li><li><span>Flagged storage</span><b>{size(report.storage_flagged_bytes)}</b></li></ul></article></section>
  <section className="panel report-section"><p className="eyebrow">LINUX REMEDIATION</p><h2>Playbook outcomes</h2>{remediation.length===0?<p className="quiet">No remediation plans yet.</p>:<div className="remediation-summary">{remediation.map(([status,count])=><div key={status}><b>{count}</b><span>{status.replaceAll("_"," ")}</span></div>)}</div>}</section>
  <section className="panel report-section"><p className="eyebrow">RISK BY DEVICE</p><h2>Where attention is needed</h2><div className="device-risk-table"><div className="device-risk-row heading"><span>Device</span><span>Agent</span><span>Active</span><span>Critical / high</span><span>CISA KEV</span><span>Failed fixes</span></div>{report.devices.map(device=><div className={`device-risk-row ${device.known_exploited||device.remediation_failed?"attention":""}`} key={device.id}><span><b>{device.name}</b><small>{device.criticality} criticality</small></span><span>{!device.agent_applicable?"Not applicable":device.agent_version?<><i className={`status-dot ${device.agent_connected?"online":"offline"}`}/>{device.agent_version}</>:"Not installed"}</span><b>{device.active_vulnerabilities}</b><b>{device.critical_high}</b><b>{device.known_exploited}</b><b>{device.remediation_failed}</b></div>)}</div></section></>;
}

function TrendChart({history}:{history:HistoricalReport}){const max=Math.max(1,...history.daily.map(x=>x.incidents+x.network_changes+x.container_alerts));return <div className="trend-chart"><div className="trend-legend"><span><i className="uptime"/>Uptime</span><span><i className="events"/>Changes and alerts</span></div><div className="trend-columns">{history.daily.map((item,index)=><div className="trend-day" key={item.date} title={`${item.date}: ${percent(item.uptime_percent)}, ${item.incidents} incidents, ${item.network_changes} network changes, ${item.container_alerts} container alerts`}><div className="trend-bars"><i className="event-bar" style={{height:`${Math.max(2,(item.incidents+item.network_changes+item.container_alerts)*100/max)}%`}}/><i className="uptime-bar" style={{height:`${item.uptime_percent??0}%`}}/></div>{(history.days<=30||index%7===0)&&<small>{new Date(`${item.date}T00:00:00`).toLocaleDateString(undefined,{month:"short",day:"numeric"})}</small>}</div>)}</div></div>}
