import { FormEvent, useState } from "react";
import { api, Device, ServiceMonitor } from "./api";

export function ServicesPage({monitors,devices,csrf,refresh}:{monitors:ServiceMonitor[];devices:Device[];csrf:string;refresh:()=>Promise<void>}){
  const [adding,setAdding]=useState(false),[editing,setEditing]=useState<ServiceMonitor|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const close=()=>{setAdding(false);setEditing(null);setError("")};
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const data=new FormData(event.currentTarget);const payload={name:data.get("name"),target_scope:data.get("scope"),url:data.get("url"),device_id:data.get("device")||null,expected_status:Number(data.get("status")),expected_text:data.get("text")||null,timeout_seconds:Number(data.get("timeout")),verify_tls:data.get("tls")==="on",enabled:data.get("enabled")==="on",severity:data.get("severity")};try{if(editing)await api.updateMonitor(editing.id,payload,csrf);else await api.createMonitor(payload,csrf);close();await refresh()}catch(reason){setError(reason instanceof Error?reason.message:"Could not save monitor")}finally{setBusy(false)}}
  return <><header><div><p className="eyebrow">AVAILABILITY</p><h1>Services</h1><p>Watch internal apps and public routes every 30 seconds.</p></div><button className="primary compact" onClick={()=>setAdding(true)}>+ Add monitor</button></header>
  {(adding||editing)&&<div className="modal-backdrop"><form className="device-form panel" onSubmit={submit}><div className="panel-title"><div><p className="eyebrow">{editing?"EDIT MONITOR":"NEW MONITOR"}</p><h2>{editing?"Update service check":"Watch a service"}</h2></div><button type="button" className="close" onClick={close}>×</button></div><p>Internal checks accept only private destinations; external checks accept only public destinations. Checks never follow redirects.</p><label>Check type<select name="scope" defaultValue={editing?.target_scope??"internal"}><option value="internal">Internal — direct LAN address</option><option value="external">External — public URL / Cloudflare</option></select></label><label>Name<input name="name" required maxLength={100} placeholder="Immich (External)" defaultValue={editing?.name}/></label><label>HTTP or HTTPS URL<input name="url" type="url" required placeholder="https://immich.example.com/" defaultValue={editing?.url}/></label><label>Related device (optional)<select name="device" defaultValue={editing?.device_id??""}><option value="">None</option>{devices.map(d=><option key={d.id} value={d.id}>{d.display_name}</option>)}</select></label><div className="form-row"><label>Expected status<input name="status" type="number" min="100" max="599" defaultValue={editing?.expected_status??200} required/></label><label>Timeout (seconds)<input name="timeout" type="number" min="1" max="30" defaultValue={editing?.timeout_seconds??5} required/></label></div><label>Expected response text (optional)<input name="text" maxLength={500} placeholder="Healthy" defaultValue={editing?.expected_text??""}/></label><label>Severity<select name="severity" defaultValue={editing?.severity??"normal"}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="critical">Critical</option></select></label><div className="check-row"><label><input name="tls" type="checkbox" defaultChecked={editing?.verify_tls??true}/> Verify TLS certificate</label><label><input name="enabled" type="checkbox" defaultChecked={editing?.enabled??true}/> Monitoring enabled</label></div>{error&&<div className="error">{error}</div>}<div className="form-actions"><button type="button" onClick={close}>Cancel</button><button className="primary compact" disabled={busy}>{busy?"Checking…":"Save and check"}</button></div></form></div>}
  {monitors.length===0?<div className="empty-state panel"><div>＋</div><h2>No service monitors yet</h2><p>Add an internal dashboard or an external public route.</p><button className="primary compact" onClick={()=>setAdding(true)}>Add your first monitor</button></div>:<div className="device-list panel"><div className="device-row service heading"><span>Service</span><span>URL</span><span>Status</span><span>Response</span><span></span></div>{monitors.map(m=><div className="device-row service" key={m.id}><span><b>{m.name}</b><small>{m.target_scope} · {m.severity} severity</small></span><span className="truncate" title={m.url}>{m.url}</span><span title={m.last_failure_reason??""}><i className={`status-dot ${m.status}`}/>{m.status}{m.outage_started_at&&<small>since {new Date(m.outage_started_at).toLocaleString()}</small>}</span><span>{m.last_response_ms?`${m.last_response_ms} ms`:"—"}<small>{m.last_status_code?`HTTP ${m.last_status_code}`:""}</small></span><div className="row-actions"><button onClick={()=>setEditing(m)}>Edit</button><button onClick={async()=>{await api.checkMonitor(m.id,csrf);await refresh()}}>Check</button><button className="danger" onClick={async()=>{if(window.confirm(`Remove ${m.name} and its check history?`)){await api.deleteMonitor(m.id,csrf);await refresh()}}}>Remove</button></div></div>)}</div>}</>;
}
