import { FormEvent, useState } from "react";
import { api, StorageTarget } from "./api";

const size = (bytes:number) => bytes >= 1_073_741_824 ? `${(bytes/1_073_741_824).toFixed(1)} GB` : `${(bytes/1_048_576).toFixed(1)} MB`;

export function StoragePage({targets,csrf,refresh}:{targets:StorageTarget[];csrf:string;refresh:()=>Promise<void>}) {
  const [adding,setAdding]=useState(false); const [busy,setBusy]=useState(""); const [error,setError]=useState("");
  async function add(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");const data=new FormData(event.currentTarget);try{await api.createStorageTarget({name:data.get("name"),relative_path:data.get("path"),large_file_mb:Number(data.get("large")),old_file_days:Number(data.get("old")),protected_paths:String(data.get("protected")||"").split("\n")},csrf);setAdding(false);await refresh()}catch(reason){setError(reason instanceof Error?reason.message:"Unable to add target")}}
  async function scan(id:string){setBusy(id);setError("");try{await api.scanStorageTarget(id,csrf);await refresh()}catch(reason){setError(reason instanceof Error?reason.message:"Scan failed")}finally{setBusy("")}}
  async function remove(id:string){if(!window.confirm("Remove this storage target and its findings? No files will be touched."))return;setBusy(id);try{await api.deleteStorageTarget(id,csrf);await refresh()}catch(reason){setError(reason instanceof Error?reason.message:"Unable to remove target")}finally{setBusy("")}}
  return <><header><div><p className="eyebrow">METADATA ONLY · READ ONLY</p><h1>Storage and bloat</h1><p>Find large and stale files inside folders mounted at <code>/scan</code>. Sentinel never reads contents or deletes files.</p></div><button className="primary compact" onClick={()=>setAdding(true)}>Add target</button></header>{error&&<div className="error storage-error">{error}</div>}{targets.length===0?<div className="empty-state panel"><h2>No storage targets</h2><p>Mount a host folder read-only with <code>STORAGE_SCAN_PATH</code>, then add <b>.</b> as your first target.</p></div>:<div className="storage-targets">{targets.map(target=><section className="panel storage-target" key={target.id}><div className="panel-title"><div><p className="eyebrow">{target.relative_path}</p><h2>{target.name}</h2><p>{target.last_scanned_at?`${target.last_file_count.toLocaleString()} files · ${size(target.last_total_bytes)} indexed`:`Not scanned yet`}</p></div><div className="row-actions"><button onClick={()=>void scan(target.id)} disabled={busy===target.id}>{busy===target.id?"Scanning…":"Scan now"}</button><button className="danger" onClick={()=>void remove(target.id)} disabled={busy===target.id}>Remove</button></div></div>{target.findings.length===0?<p className="quiet">No recommendations yet.</p>:<div className="storage-findings">{target.findings.map(item=><div className="storage-row" key={item.id}><div><b>{item.relative_path}</b><small>{item.reason} · modified {new Date(item.modified_at).toLocaleDateString()}</small></div><strong>{size(item.size_bytes)}</strong>{item.protected&&<span>Protected</span>}</div>)}</div>}</section>)}</div>}{adding&&<div className="modal-backdrop"><form className="panel device-form" onSubmit={add}><div className="panel-title"><div><p className="eyebrow">READ-ONLY TARGET</p><h2>Add storage target</h2></div><button type="button" className="close" onClick={()=>setAdding(false)}>×</button></div><p>Paths are relative to the folder mounted at <code>/scan</code>.</p><label>Name<input name="name" placeholder="Media library" required maxLength={100}/></label><label>Relative path<input name="path" defaultValue="." required/></label><div className="form-row"><label>Large file threshold (MB)<input name="large" type="number" defaultValue="1024" min="1" required/></label><label>Old file threshold (days)<input name="old" type="number" defaultValue="365" min="1" required/></label></div><label>Protected paths (one per line)<textarea name="protected" rows={4} placeholder={"family-photos\nbackups/current"}/></label><div className="form-actions"><button type="button" onClick={()=>setAdding(false)}>Cancel</button><button className="primary compact">Add target</button></div></form></div>}</>;
}
