import { useMemo, useState } from "react";
import { api, VulnerabilityFinding } from "./api";

const statuses=["open","investigating","accepted_risk","false_positive","resolved","ignored"];
const label=(value:string)=>value.replaceAll("_"," ");

export function VulnerabilitiesPage({findings,csrf,updateFinding}:{findings:VulnerabilityFinding[];csrf:string;updateFinding:(finding:VulnerabilityFinding)=>void}) {
  const [statusFilter,setStatusFilter]=useState("active"),[severity,setSeverity]=useState("all"),[host,setHost]=useState("all"),[priority,setPriority]=useState("all"),[groupBy,setGroupBy]=useState("none"),[query,setQuery]=useState("");
  const hosts=[...new Set(findings.map(f=>f.address))].sort();
  const visible=useMemo(()=>findings.filter(f=>(statusFilter==="all"||(statusFilter==="active"?["open","investigating"].includes(f.status):f.status===statusFilter))&&(severity==="all"||f.severity===severity)&&(host==="all"||f.address===host)&&(priority==="all"||(priority==="kev"&&f.known_exploited))&&(!query||`${f.cve_id} ${f.description} ${f.cpe}`.toLowerCase().includes(query.toLowerCase()))),[findings,statusFilter,severity,host,priority,query]);
  const groups=useMemo(()=>{if(groupBy==="none")return [["All findings",visible]] as [string,VulnerabilityFinding[]][];const key=(f:VulnerabilityFinding)=>groupBy==="host"?f.address:groupBy==="severity"?f.severity:f.status;return [...new Set(visible.map(key))].sort().map(value=>[label(value),visible.filter(f=>key(f)===value)] as [string,VulnerabilityFinding[]])},[visible,groupBy]);
  async function changeStatus(finding:VulnerabilityFinding,status:string){updateFinding(await api.updateFinding(finding.id,status,finding.user_notes,csrf))}
  return <><header><div><p className="eyebrow">EVIDENCE-BASED FINDINGS</p><h1>Vulnerabilities</h1><p>Exact CPE matches with triage and CISA exploitation priority.</p></div></header><div className="notice panel">This product uses data from the NVD API but is not endorsed or certified by the NVD.</div>{findings.length===0?<div className="empty-state panel"><h2>No findings yet</h2><p>Inspect a host in Discovery, then run its vulnerability lookup when CPE evidence is available.</p></div>:<><div className="panel finding-filters"><label>Search<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="CVE, product, or text"/></label><label>Status<select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="active">Active</option><option value="all">All</option>{statuses.map(s=><option value={s} key={s}>{label(s)}</option>)}</select></label><label>Severity<select value={severity} onChange={e=>setSeverity(e.target.value)}><option value="all">All</option>{["critical","high","medium","low","unknown"].map(s=><option key={s}>{s}</option>)}</select></label><label>Device<select value={host} onChange={e=>setHost(e.target.value)}><option value="all">All</option>{hosts.map(address=><option key={address}>{address}</option>)}</select></label><label>Priority<select value={priority} onChange={e=>setPriority(e.target.value)}><option value="all">All</option><option value="kev">CISA KEV only</option></select></label><label>Group by<select value={groupBy} onChange={e=>setGroupBy(e.target.value)}><option value="none">None</option><option value="host">Device</option><option value="severity">Severity</option><option value="status">Status</option></select></label><b>{visible.length} of {findings.length}</b></div>{visible.length===0?<div className="empty-state panel"><h2>No matching findings</h2><p>Change or clear the filters above.</p></div>:groups.map(([name,items])=><section className="finding-bucket" key={name}><h2>{groupBy==="none"?null:<>{name}<span>{items.length}</span></>}</h2><div className="finding-grid">{items.map(f=><article className={`panel finding ${f.known_exploited?"kev":""}`} key={f.id}><div><span className={`severity ${f.severity}`}>{f.severity}</span><b>{f.cve_id}</b>{f.known_exploited&&<span className="kev-badge">CISA KEV</span>}<small>CVSS {f.cvss_score||"unscored"}</small><select value={f.status} onChange={e=>void changeStatus(f,e.target.value)}>{statuses.map(s=><option value={s} key={s}>{label(s)}</option>)}</select></div><p>{f.description}</p>{f.required_action&&<p className="required-action"><b>Required action:</b> {f.required_action}{f.action_due&&` · Due ${f.action_due}`}</p>}<small>{f.address} · {f.cpe}</small></article>)}</div></section>)}</>}</>;
}
